# Generated by Django 4.0.5 on 2022-06-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_alter_docente_options_remove_docente_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='fecha_nacimiento',
            field=models.DateTimeField(verbose_name='Fecha de Naciminto'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='genero',
            field=models.CharField(default='Otro', max_length=10, verbose_name='Género'),
        ),
    ]
